apiVersion: v1
kind: Pod
metadata:
  name: secure-app
  namespace: secure-workloads
  labels:
    app: secure-app
    environment: lab
spec:
  containers:
  - name: app
    image: node:16-alpine
    imagePullPolicy: Never
    command: ["node", "-e", "setInterval(() => {}, 1000)"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
  restartPolicy: Never
