apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: myapp
    image: nginx:1.21
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: user-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: user-credentials
          key: password
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: db-host
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Username: '$DB_USERNAME; echo 'Host: '$DATABASE_HOST; sleep 30; done"]
