FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    openssl \
    python3 \
    && rm -rf /var/lib/apt/lists/*

COPY app.py /app/
WORKDIR /app

CMD ["python3", "app.py"]
