apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: restricted-test
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: client
    image: busybox
    command: ["sh", "-c", "while true; do wget -qO- http://secure-web-service; sleep 5; done"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
